# Site settings
author: Taroj Khan
title: Why I chose Software Engineering
header-img: img/home-bg.png
email: tarujkhan@yahoo.com
copyright_name: Taroj Khan
description: > # this means to ignore newlines until "baseurl:"
  My interest
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tarujkhan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
